name: Build LaTeX

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Build PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: report

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: report/main.pdf
